### ISSUE TITLE
Tests for each provider

### ISSUE THREAD

**Issue by ArdenHide** [The-Poolz/LockDeal-NFT-API#111]
### Simple:
- [ ] #112
- [ ] [LockDealProvider](https://github.com/The-Poolz/LockDeal-NFT-API/blob/master/src/MetaDataAPI/Providers/Simple/LockDealProvider.cs)
- [ ] [TimedDealProvider](https://github.com/The-Poolz/LockDeal-NFT-API/blob/master/src/MetaDataAPI/Providers/Simple/TimedDealProvider.cs)

### Advanced: 
- [ ] [RefundProvider](https://github.com/The-Poolz/LockDeal-NFT-API/blob/master/src/MetaDataAPI/Providers/Advanced/RefundProvider.cs)
- [ ] [CollateralProvider](https://github.com/The-Poolz/LockDeal-NFT-API/blob/master/src/MetaDataAPI/Providers/Advanced/CollateralProvider.cs)
- [ ] [BundleProvider](https://github.com/The-Poolz/LockDeal-NFT-API/blob/master/src/MetaDataAPI/Providers/Advanced/BundleProvider.cs)

**Comment by Lomet** [comment]
> we got 100% test coverage, we got tested the providers here:
> 
> https://github.com/The-Poolz/LockDeal-NFT-API/blob/8e05e10b7b9fd2a816108eecc893482f208adb15/tests/MetaDataAPI.Tests/LambdaFunctionTests.cs#L30

add the assets in the same place.
