### ISSUE TITLE
`ERC20` with `Net.Cache`

### ISSUE THREAD

**Issue by Lomet** [The-Poolz/LockDeal-NFT-API#232]
use the erc https://github.com/The-Poolz/Net.Cache

**Comment by ArdenHide** [comment]
Use already exist implementation in [Net.Cache.DynamoDb.ERC20](https://github.com/The-Poolz/Net.Cache/tree/master/src/Net.Cache.DynamoDb.ERC20) library, instead of `Erc20Token` class

**Comment by ArdenHide** [comment]
Before start completing this issue, need to close this issue: https://github.com/The-Poolz/LockDeal-NFT-API/issues/244
To use [Net.Cache.DynamoDb.ERC20](https://github.com/The-Poolz/Net.Cache/tree/master/src/Net.Cache.DynamoDb.ERC20) need to have a ChainId and RpcUrl.
